name: sativus
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.1.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_ui_localizations: ^1.5.0
  http: '>=0.13.0 <2.0.0'
  hydrated_state_notifier: ^1.0.0
  riverpod: ^2.3.6
  flutter_riverpod: ^2.3.6
  responsivebility: ^0.1.1
  google_fonts: ^5.1.0
  path_provider: ^2.0.15
  path: ^1.8.3
  go_router: ^8.2.0
  flex_color_scheme: ^7.1.2
  flutter_svg: ^2.0.7
  intl: ^0.18.0
  badges: ^3.1.1
  logging: ^1.2.0
  json_annotation: ^4.8.1
  hydrated_state_notifier_hive: ^1.0.0
  freezed_annotation: ^2.2.0
  image_picker: ^0.8.9
  cross_file: ^0.3.3+4
  url_launcher: ^6.1.11
  handle: ^0.3.4+1
  equatable: ^2.0.5
  pointycastle: ^3.7.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.5
  flutter_gen_runner: ^5.3.1
  json_serializable: ^6.7.0
  freezed: ^2.3.5
  mason_logger: ^0.2.6

flutter:
  uses-material-design: true
  generate: true

flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)
  # Optional
  integrations:
    flutter_svg: true

scripts:
  win: flutter run -d windows --dart-define-from-file=.\dart-define\dev.json
  linux: flutter run -d linux --dart-define-from-file=./dart-define/dev.json
  l10n: flutter gen-l10n
